AllCops:
  Exclude:
    - spec/**/*.rb
    - bin/**/*

Metrics/LineLength:
  Max: 100

Style/Documentation:
  Enabled: no

Style/AsciiComments:
  Enabled: no

Naming/PredicateName:
  Enabled: no

Style/NumericPredicate:
  Enabled: no

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
