sudo: false
language: ruby
rvm:
  - 2.2.10
  - 2.3
  - 2.4
  - 2.5

before_install:
  - gem install bundler -v 1.16.2
install:
  - bundle install --jobs=3 --retry=3
before_script:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec --warnings --order random
  - bundle exec rubocop -DESP
  - bundle exec rubycritic -f console -s 90 lib/
  - bundle exec fasterer lib || true
after_script: if ! $TRAVIS_PULL_REQUEST; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi

notifications:
  - false

branches:
  only:
    - master

jobs:
  include:
    - stage: Deploy Docs
      before_install: skip
      install: skip
      before_script: skip
      script: bash ./deploy-docs.sh
      after_script: skip

stages:
  - Test
  - name: Deploy Docs
    if: branch = master AND type != pull_request
