sudo: false
language: ruby
env:
  global:
    COVERAGE=1
    CC_TEST_REPORTER_ID=2ed4169686262bba86b94f45f05a5f9dcc00226feb75e3928563914a066512d6
rvm:
  - 2.2

before_install:
  - gem install bundler -v 1.16.2
install:
  - bundle install --jobs=3 --retry=3

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rubocop -DESP
  - bundle exec rubycritic -f console -s 90 lib/
  - bundle exec rspec --warnings --order random
  - bundle exec fasterer lib || true
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

notifications:
  - false
